# Generated by Django 4.1.6 on 2023-04-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Bio',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
