version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  test-env:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run:
          name: "Set environment variables"
          command: |
            echo "export HEROKU_API_KEY=$HEROKU_API_KEY" >> $BASH_ENV
            echo "export HEROKU_APP_NAME=$HEROKU_APP_NAME" >> $BASH_ENV
            echo "export HEROKU_FRONTEND_APP_NAME=$HEROKU_FRONTEND_APP_NAME" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: "Print environment variables"
          command: |
            echo $HEROKU_API_KEY
            echo $HEROKU_APP_NAME
            echo $HEROKU_FRONTEND_APP_NAME
            echo $(git remote -v)
  deploy-backend:
    executor: heroku/default
    resource_class: small
    steps:
        - checkout
        - run:
            name: "Set environment variables"
            command: |
              echo "export HEROKU_API_KEY=$HEROKU_API_KEY" >> $BASH_ENV
              echo "export HEROKU_APP_NAME=$HEROKU_APP_NAME" >> $BASH_ENV
              source $BASH_ENV
        - heroku/deploy-via-git:
            app-name: $HEROKU_APP_NAME
            api-key: HEROKU_API_KEY
            force: true
            # post-steps:
            #   - run: |
            #       echo "Running post-deployment steps on Heroku"
            #       python manage.py makemigrations
            #       python manage.py migrate
            # pre-steps:
            #   - run: |
            #       echo "Running pre-deployment steps on Heroku"
            #       # python manage.py collectstatic --noinput
            # requires:
            #   - build-backend
            # filters:
            #   branches:
            #     only:
            #       - CICDTest
  deploy-frontend:
      executor: heroku/default
      resource_class: small
      steps:
        - checkout
        - run:
            name: "Set environment variables"
            command: |
              echo "export HEROKU_API_KEY=$HEROKU_API_KEY" >> $BASH_ENV
              echo "export HEROKU_FRONTEND_APP_NAME=$HEROKU_FRONTEND_APP_NAME" >> $BASH_ENV
              echo $HEROKU_FRONTEND_APP_NAME
              source $BASH_ENV
        - heroku/deploy-via-git:
            app-name: $HEROKU_FRONTEND_APP_NAME
            api-key: HEROKU_API_KEY
            force: true
            # post-steps:
            #   - run: |
            #       echo "Running post-deployment steps on Heroku"
            # pre-steps:
            #   - run: |
            #       echo "Running pre-deployment steps on Heroku"
            #       # May need to run npm build here
            #       # and then copy the build folder to the root of the project
            # requires:
            #   - build-frontend
            # filters:
            #   branches:
            #     only:
            #       - CICDTest
  build-frontend:
    docker:
      - image: cimg/node:18.12.1
    resource_class: small
    working_directory: ~/project/frontend
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: |
          cd frontend
          echo "Installing React dependencies"
          npm install
          echo "Running React tests"
          npm test
      - store_test_results:
          path: frontend/test-results
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
    # parallelism: 2
  build-backend:
    docker:
      - image: circleci/python:3.9
    resource_class: small
    working_directory: ~/project/backend
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      - run: |
          cd backend
          echo "Creating virtual environment"
          python -m venv venv
          python -m pip install --upgrade pip
          source venv/bin/activate
          echo "Installing Python dependencies"
          pip install -r requirements.txt
          # echo "Running Python tests"
          # pytest
      - store_test_results:
          path: backend/test-results
      - save_cache:
          paths:
            - venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
    # parallelism: 2

workflows:
  test-env:
    jobs:
      - test-env
  build-test-deploy-frontend:
    jobs:
      - build-frontend
      - deploy-frontend:
          requires:
            - build-frontend
          filters:
            branches:
              only:
                - CICDTest
  build-test-deploy-backend:
    jobs:
      - build-backend
      - deploy-backend:
          requires:
            - build-backend
          filters:
            branches:
              only:
                - CICDTest
