version: 2.1
jobs:
  build-frontend:
    docker:
      - image: cimg/node:18.12.1
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: |
          cd frontend
          npm install
          npm test
      - store_test_results:
          path: frontend/test-results
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: |
          cd frontend
          npm run build
      - deploy:
          name: Deploy Frontend
          command: |
            echo "Deploying frontend to Heroku"
            echo "We're in ${PWD}"
            cd frontend
            git init .
            git config user.email "deploy@circleci.com"
            git config user.name "CircleCI Deploy"
            git add .
            git commit -m "Deploy frontend to Heroku"
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_BACKEND_APP_NAME.git main
    parallelism: 2
  build-backend:
    docker:
      - image: circleci/python:3.9
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      - run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest
      - store_test_results:
          path: backend/test-results
      - save_cache:
          paths:
            - venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run: |
          cd backend
          python manage.py makemigrations
          python manage.py migrate
          python manage.py collectstatic --noinput
      - deploy:
          name: Deploy Backend
          command: |
            echo "Deploying backend to Heroku"
            git init .
            git config user.email "deploy@circleci.com"
            git config user.name "CircleCI Deploy"
            git add .
            git commit -m "Deploy backend to Heroku"
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
workflows:
  build-and-deploy:
    jobs:
      - build-frontend:
          filters:
            branches:
              only:
                - CICDTest
      - build-backend:
          requires:
            - build-frontend
          filters:
            branches:
              only:
                - CICDTest
